services:
  mongo:
    container_name: mongodb
    image: registry.cn-hangzhou.aliyuncs.com/voyo/linux_arm64_mongo:7.0.11
    ports:
      - "27017:27017"
    volumes:
      - /home/mongodb:/var/lib/mongo
    logging:
      driver: "json-file"
      options:
        max-size: "2048k"
        max-file: 10

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xxxxx

    command: --config /var/lib/mongo/mongod.conf
